remote_theme: pages-themes/leap-day@v0.2.0

title: Recipe Reviews Data Analysis
description: An analysis of reviews of recipes using machine learning predictions and other data exploration.
plugins:
  - jekyll-remote-theme