remote_theme: pages-themes/leap-day@v0.2.0

title: Food Reviews Data Analysis
description: This is a project where I investigate recipe reviews using hypothesis tests and machine learning-based predictions.
plugins:
  - jekyll-remote-theme